on:
  workflow_dispatch:

env:
  LABELBOX_API_KEY: ${{ secrets.LABELBOX_API_KEY }}

jobs:
  populate_workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - id: download labelbox
        run: pip install labelbox
      - id: import data rows
        run: python import.py
      - id: import geospatial
        run: python import_tile.py
